# Generated by Django 5.2.12 on 2026-03-11 03:21

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AgentTask',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('task_type', models.CharField(choices=[('product_publish', '商品上新'), ('store_deactivate', '门店下架')], max_length=30, verbose_name='任务类型')),
                ('status', models.CharField(choices=[('pending', '待确认'), ('confirmed', '已确认'), ('running', '执行中'), ('done', '已完成'), ('failed', '失败'), ('cancelled', '已取消')], default='pending', max_length=20, verbose_name='状态')),
                ('celery_task_id', models.CharField(blank=True, max_length=255, verbose_name='Celery ID')),
                ('scheduled_at', models.DateTimeField(verbose_name='计划执行时间')),
                ('executed_at', models.DateTimeField(blank=True, null=True, verbose_name='实际执行时间')),
                ('confirmed_by', models.CharField(blank=True, max_length=100, verbose_name='确认人')),
                ('payload', models.JSONField(default=dict, verbose_name='任务参数')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
            ],
            options={
                'verbose_name': 'Agent 任务',
                'verbose_name_plural': '任务队列',
                'ordering': ['-created_at'],
            },
        ),
    ]
