# Generated by Django 5.2.12 on 2026-03-11 04:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='InboundEmail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject', models.CharField(max_length=512, verbose_name='邮件标题')),
                ('sender', models.CharField(max_length=255, verbose_name='发件人')),
                ('intent', models.CharField(choices=[('product_update', '商品更新'), ('store_deactivate', '门店下架'), ('unknown', '未知')], default='unknown', max_length=30, verbose_name='意图')),
                ('parsed_schedule', models.DateTimeField(blank=True, null=True, verbose_name='解析出的执行时间')),
                ('attachment_path', models.CharField(blank=True, max_length=512, verbose_name='附件路径')),
                ('raw_body', models.TextField(blank=True, verbose_name='邮件正文')),
                ('received_at', models.DateTimeField(verbose_name='收件时间')),
                ('processed', models.BooleanField(default=False, verbose_name='已处理')),
            ],
            options={
                'verbose_name': '收件记录',
                'verbose_name_plural': '收件记录',
                'ordering': ['-received_at'],
            },
        ),
    ]
