# Generated by Django 5.2.12 on 2026-03-11 03:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('tasks', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='OperationLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(max_length=100, verbose_name='操作类型')),
                ('target_type', models.CharField(max_length=50, verbose_name='对象类型')),
                ('target_id', models.CharField(max_length=100, verbose_name='对象ID')),
                ('result', models.CharField(choices=[('success', '成功'), ('failed', '失败'), ('skipped', '已跳过')], max_length=20, verbose_name='结果')),
                ('detail', models.TextField(blank=True, verbose_name='详情')),
                ('screenshot_path', models.CharField(blank=True, max_length=512, verbose_name='截图路径')),
                ('operator', models.CharField(default='system', max_length=100, verbose_name='操作人')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='日志时间')),
                ('task', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='logs', to='tasks.agenttask', verbose_name='关联任务')),
            ],
            options={
                'verbose_name': '操作日志',
                'verbose_name_plural': '操作日志',
                'ordering': ['-created_at'],
            },
        ),
    ]
