# Generated by Django 5.2.12 on 2026-03-11 03:21

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Store',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('store_code', models.CharField(max_length=64, unique=True, verbose_name='门店编号')),
                ('name', models.CharField(max_length=255, verbose_name='门店名称')),
                ('region', models.CharField(blank=True, max_length=100, verbose_name='地区')),
                ('saleor_channel_id', models.CharField(blank=True, max_length=128, verbose_name='Saleor ID')),
                ('status', models.CharField(choices=[('active', '正常营业'), ('deactivating', '下架中'), ('inactive', '已下架')], default='active', max_length=20, verbose_name='状态')),
                ('deactivated_at', models.DateTimeField(blank=True, null=True, verbose_name='下架时间')),
                ('screenshot_path', models.CharField(blank=True, max_length=512, verbose_name='验证截图')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
            ],
            options={
                'verbose_name': '门店',
                'verbose_name_plural': '门店列表',
                'ordering': ['-created_at'],
            },
        ),
    ]
