# Generated by Django 5.2.12 on 2026-03-11 03:21

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sku', models.CharField(max_length=64, unique=True, verbose_name='SKU')),
                ('name', models.CharField(blank=True, max_length=255, verbose_name='商品名')),
                ('category', models.CharField(blank=True, max_length=100, verbose_name='品类')),
                ('spec', models.CharField(blank=True, max_length=255, verbose_name='规格')),
                ('price', models.DecimalField(decimal_places=2, max_digits=10, null=True, verbose_name='售价')),
                ('generated_title', models.CharField(blank=True, max_length=100, verbose_name='生成标题')),
                ('generated_desc', models.TextField(blank=True, verbose_name='生成描述')),
                ('missing_fields', models.JSONField(default=list, verbose_name='缺失字段')),
                ('status', models.CharField(choices=[('draft', '草稿（字段缺失）'), ('pending', '待人工确认'), ('reviewing', '待执行'), ('published', '已上新')], default='draft', max_length=20, verbose_name='状态')),
                ('scheduled_at', models.DateTimeField(blank=True, null=True, verbose_name='计划上新时间')),
                ('published_at', models.DateTimeField(blank=True, null=True, verbose_name='实际上新时间')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
            ],
            options={
                'verbose_name': '商品',
                'verbose_name_plural': '商品列表',
                'ordering': ['-created_at'],
            },
        ),
    ]
